//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.RelToTarget = new HashSet<Relation>();
            this.RelFromSource = new HashSet<Relation>();
            this.ControlElements = new HashSet<ControlElement>();
            this.Questions = new HashSet<Question>();
            this.AttributeValues = new HashSet<AttributeValue>();
            this.Conditions = new HashSet<Condition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Specification { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Relation> RelToTarget { get; set; }
        public virtual ICollection<Relation> RelFromSource { get; set; }
        public virtual ICollection<ControlElement> ControlElements { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<AttributeValue> AttributeValues { get; set; }
        public virtual ICollection<Condition> Conditions { get; set; }
    }
}
