//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystem1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaseModelContainer : DbContext
    {
        public CaseModelContainer()
            : base("name=CaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Entity> EntitySet { get; set; }
        public DbSet<Attribute> AttributeSet { get; set; }
        public DbSet<Relation> RelationSet { get; set; }
        public DbSet<Forma> FormaSet { get; set; }
        public DbSet<ControlElement> ControlElementSet { get; set; }
        public DbSet<TypeControlElement> TypeControlElementSet { get; set; }
        public DbSet<TypeEvent> TypeEventSet { get; set; }
        public DbSet<Question> QuestionSet { get; set; }
        public DbSet<Condition> ConditionSet { get; set; }
        public DbSet<Report> ReportSet { get; set; }
        public DbSet<AttributeValue> AttributeValueSet { get; set; }
        public DbSet<DataBaseProject> DataBaseProjectSet { get; set; }
    }
}
