//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int Id { get; set; }
        public bool Not { get; set; }
        public string Compare { get; set; }
        public string Value { get; set; }
        public string Operation { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Attribute Attribute { get; set; }
    }
}
