//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlElement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public int Length { get; set; }
        public int Width { get; set; }
    
        public virtual Forma Forma { get; set; }
        public virtual TypeControlElement TypeControlElement { get; set; }
        public virtual Attribute Attribute { get; set; }
    }
}
