//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystem1
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Office.Interop;
    public partial class Report
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Format { get; set; }
    
        public virtual Question Question { get; set; }
        public bool SaveReport(int projId, string pathToXML)
        {
            List<string> resOfQue = Question.Execute();
            if (resOfQue.Count != 0)
            {
                switch (Format)
                {
                    case "MS Word":
                        //Microsoft.Office.Interop.Word.Application apl = new Interop.Word.Application();
                        break;
                    case "MS Excel":
                        Microsoft.Office.Interop.Excel.Application appl = new Microsoft.Office.Interop.Excel.Application();
                        Microsoft.Office.Interop.Excel.Workbook workBook;
                        Microsoft.Office.Interop.Excel.Worksheet sheet;
                        //Книга
                        workBook = appl.Workbooks.Add(System.Reflection.Missing.Value);
                        //Таблица
                        sheet = (Microsoft.Office.Interop.Excel.Worksheet)workBook.Worksheets.get_Item(1);
                        int rowExcel = 1;
                        //Worksheet sheet = (Worksheet)exApp.ActiveSheet; //новый лист
                        foreach (Attribute at in Question.Attributes)
                        {
                            int columnExcel = 1;
                            sheet.Cells[rowExcel, columnExcel] = at.Name;
                            foreach (AttributeValue atv in at.AttributeValues)
                            {
                                if (resOfQue.Contains(atv.Attribute.Entity.Id + "." + atv.Number))
                                {
                                    sheet.Cells[rowExcel, columnExcel + 1] = atv.Value;
                                    columnExcel++;
                                }
                            }
                            rowExcel++;
                        }
                        sheet.SaveAs(pathToXML);    //сохранение файла
                        appl.Quit();   //закрытие файла
                                       //MessageBox.Show("Сформирован отчет - " + ReportName.Text, "Отчет. Успешно", MessageBoxButtons.OK);
                                       //Report newRt = new Report();
                                       //newRt.Name = ReportName.Text;
                                       //newRt.Description = pathToXML;
                                       //currentQuest.Reports.Add(newRt);
                                       //cont.ReportSet.Add(newRt);
                                       //Hide();
                                       //FrMain main = new FrMain();
                                       //main.currentDBS = dBP.Id;
                                       //main.ShowDialog();
                                       //Close();
                        break;
                }
                return true;
            }
            else
                return false;
        }
        public void OpenReport()
        {

        }
    }
}
